### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/libefifstr_1e0589b3.so: undefined symbol

### ISSUE THREAD

**Issue by ximzzzzz** [Actasidiot/EFIFSTR#1]
hello, 
i got error while  "python eval.py".  i already build, and my python, tf version are same with you.
any idea to solve this error?
details are below

-------------

root@5fcb139ce75e:/tf/FoodDetection/AI_OCR/EFIFSTR# python eval.py
Traceback (most recent call last):
  File "eval.py", line 7, in <module>
    import evaluator
  File "/tf/FoodDetection/AI_OCR/EFIFSTR/evaluator.py", line 7, in <module>
    from core import preprocessor
  File "/tf/FoodDetection/AI_OCR/EFIFSTR/core/preprocessor.py", line 8, in <module>
    from c_ops import ops
  File "/tf/FoodDetection/AI_OCR/EFIFSTR/c_ops/ops.py", line 26, in <module>
    _oplib = _load_oplib(FLAGS.oplib_name)
  File "/tf/FoodDetection/AI_OCR/EFIFSTR/c_ops/ops.py", line 23, in _load_oplib
    oplib = tf.load_op_library(lib_copy_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/libefifstr_385c0974.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by ximzzzzz** [comment]
after build in conda environment problem fixed !!
don't forget to build in conda

**Comment by Actasidiot** [comment]
> after build in conda environment problem fixed !!
> don't forget to build in conda

Thank you for your suggestions. Seems it must be built with conda.
